### ISSUE TITLE
Overleafでの動作検証について

### ISSUE THREAD

**Issue by shnhrtkyk** [hydrocoast/JSCE_LaTeX#2]
forkしまして、overleaf上での動作検証を行いました。  
その際に、latexmkrcというファイルをoverleafで作成し、そこへ以下のスクリプトを書くとコンパイルできました。  
```
$latex = 'uplatex';
$bibtex = 'upbibtex';
$dvipdf = 'dvipdfmx -p a4 %O -o %D %S';
$makeindex = 'mendex -U %O -o %D %S';
$pdf_mode = 3; 
```
注意点として、overleafのコンパイラの設定をLaTexに変更する必要がありました。

**Comment by hydrocoast** [comment]
検証ありがとうございます．  
このパッケージに追加しても良さそうです．

仕様をよく理解していないのですが，Overleaf だとファイル名は .latexmkrc ではなくて latexmkrc である必要があるんでしょうか？

**Comment by shnhrtkyk** [comment]
まず，テンプレートを作製していただきましてありがとうございました．
非常に助かりました．

該当ファイルのプルリクエトを作製してみました．
また，Overleafではこのように見えます．
[Overleaf](https://www.overleaf.com/read/hkpbrkbbbskm)

**Comment by hydrocoast** [comment]
良い感じですね．PRをマージしました．  
ただし README にもあるように LaTeX 版は土木学会公式のサポートが切れているのでご注意ください．  
[各種書式（土木学会）](https://committees.jsce.or.jp/jjsce/pform)

私がよく提出する土木学会の委員会では，今のところまだ LaTeX でも大丈夫そうですが．

**Comment by shnhrtkyk** [comment]
なるほど......気をつけたいと思います
